project_name: terraform-provider-incidentrelay

builds:
  - id: terraform-provider-incidentrelay
    binary: terraform-provider-incidentrelay
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

